name: subset-construction
version: 0.1.0.0
github: "AlexisGado/subset-construction"
license: BSD3
author: "Alexis Gadonneix"
maintainer: "ag4625@columbia.edu"
copyright: "2022 Alexis Gadonneix"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - assets/**

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/subset-construction#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - random
  - parsec
  - parallel
  - deepseq
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  subset-construction-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -eventlog
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - subset-construction

tests:
  subset-construction-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - subset-construction
